networks:
  backend-network:
    driver: bridge
    name: backend-network

services:
  postgres:
    image: postgres:16-alpine
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    networks:
      - backend-network

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    ports:
      - 8080:80
    environment:
      - POSTGRES_URL
    depends_on:
      - postgres
    networks:
      - backend-network